// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0J_xq0eFBm6l1hZccp5vS65CjeMhiAQ',
    appId: '1:1057436707640:web:5c516aa2e9028e5437efcd',
    messagingSenderId: '1057436707640',
    projectId: 'harvest-institute-app',
    authDomain: 'harvest-institute-app.firebaseapp.com',
    storageBucket: 'harvest-institute-app.firebasestorage.app',
    measurementId: 'G-9ZGE8Y281P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJutwGWl8XoKkqlB1YZjNFTWlr1_5VQcE',
    appId: '1:1057436707640:android:097973228b077fa537efcd',
    messagingSenderId: '1057436707640',
    projectId: 'harvest-institute-app',
    storageBucket: 'harvest-institute-app.firebasestorage.app',
  );
}
